# Generated by Django 4.2 on 2023-04-21 13:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('regional', models.CharField(choices=[('1ª Regional - João Pessoa', '1ª Regional - João Pessoa'), ('2ª Regional - Guarabira', '2ª Regional - Guarabira'), ('3ª Regional - Campina Grande', '3ª Regional - Campina Grande'), ('4ª Regional - Cuité', '4ª Regional - Cuité'), ('5ª Regional - Monteiro', '5ª Regional - Monteiro'), ('6ª Regional - Patos', '6ª Regional - Patos'), ('7ª Regional - Itaporanga', '7ª Regional - Itaporanga'), ('8ª Regional - Catolé do Rocha', '8ª Regional - Catolé do Rocha'), ('9ª Regional - Cajazeiras', '9ª Regional - Cajazeiras'), ('10ª Regional - Sousa', '10ª Regional - Sousa'), ('11ª Regional - Princesa Isabel', '11ª Regional - Princesa Isabel'), ('12ª Regional - Itabaiana', '12ª Regional - Itabaiana'), ('13ª Regional - Pombal', '13ª Regional - Pombal'), ('14ª Regional - Mamanguape', '14ª Regional - Mamanguape')], max_length=40, verbose_name='Regional')),
                ('level', models.CharField(choices=[('Fundamental', 'Fundamental'), ('Médio', 'Médio'), ('Superior', 'Superior')], max_length=20, verbose_name='Nível')),
                ('governance', models.CharField(choices=[('Municipal', 'Municipal'), ('Estadual', 'Estadual'), ('Federal', 'Federal'), ('Particular', 'Particular')], max_length=20, verbose_name='Gestão')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado em')),
            ],
        ),
    ]
